const {
  joinVoiceChannel,
  createAudioPlayer,
  createAudioResource,
  AudioPlayerStatus,
  VoiceConnectionStatus,
} = require('@jubbio/voice');
const ytSearch = require('yt-search');

// guildId → { connection, player, queue, current, textChannelSend }
const sessions = new Map();

function getSession(guildId) {
  return sessions.get(guildId) || null;
}

function deleteSession(guildId) {
  const s = sessions.get(guildId);
  if (s) {
    try { s.player.stop(true); } catch {}
    try { s.connection.destroy(); } catch {}
    sessions.delete(guildId);
  }
}

function videoToTrack(v) {
  return {
    title: v.title,
    url: v.url,
    duration: v.timestamp || 'unknown',
    thumbnail: v.thumbnail || null,
  };
}

async function resolveTrack(query) {
  const isUrl = /^https?:\/\//i.test(query);

  if (isUrl) {
    return { title: query, url: query, duration: 'unknown', thumbnail: null };
  }

  // Run all three searches in parallel for speed
  const [topicResults, officialResults, rawResults] = await Promise.all([
    ytSearch(`${query} - Topic`).then(r => r.videos || []),
    ytSearch(`${query} official audio`).then(r => r.videos || []),
    ytSearch(query).then(r => r.videos || []),
  ]);

  // Strategy 1: a result from a genuine YouTube "- Topic" channel.
  // These channels are auto-generated by YouTube Music and are always named
  // exactly "<Artist> - Topic" — the most reliable source for music.
  const topicVideo = topicResults.find(v => v.author?.name?.endsWith('- Topic'));
  if (topicVideo) {
    console.log(`[Search] Topic channel: "${topicVideo.title}" by ${topicVideo.author?.name}`);
    return videoToTrack(topicVideo);
  }

  // Strategy 2: a result with "official audio" / "official video" / "lyrics" in the title
  // from the official audio search — prioritise exact artist name matches.
  const officialVideo = officialResults.find(v => {
    const t = v.title.toLowerCase();
    return t.includes('official') || t.includes('lyrics') || t.includes('audio');
  }) || officialResults[0];
  if (officialVideo) {
    console.log(`[Search] Official: "${officialVideo.title}"`);
    return videoToTrack(officialVideo);
  }

  // Strategy 3: bare query fallback — just take the top result
  const fallback = rawResults[0];
  if (!fallback) throw new Error('No results found for that query.');

  console.log(`[Search] Fallback: "${fallback.title}"`);
  return videoToTrack(fallback);
}

function waitForReady(connection, timeoutMs = 30_000) {
  return new Promise((resolve, reject) => {
    if (connection.state.status === VoiceConnectionStatus.Ready) {
      return resolve();
    }

    const timer = setTimeout(() => {
      connection.off('stateChange', onStateChange);
      reject(new Error('Voice connection timed out waiting for Ready state.'));
    }, timeoutMs);

    function onStateChange(oldState, newState) {
      if (newState.status === VoiceConnectionStatus.Ready) {
        clearTimeout(timer);
        connection.off('stateChange', onStateChange);
        resolve();
      } else if (
        newState.status === VoiceConnectionStatus.Destroyed ||
        newState.status === VoiceConnectionStatus.Disconnected
      ) {
        clearTimeout(timer);
        connection.off('stateChange', onStateChange);
        reject(new Error(`Voice connection entered ${newState.status} state.`));
      }
    }

    connection.on('stateChange', onStateChange);
  });
}

async function joinChannel(guild, voiceChannelId, textChannelSend) {
  let session = getSession(guild.id);

  if (session) {
    session.textChannelSend = textChannelSend;
    return session;
  }

  const adapterCreator = guild.voiceAdapterCreator;
  if (!adapterCreator) {
    throw new Error('Voice adapter not ready for this guild yet — please try again in a moment.');
  }

  console.log(`[Voice] Joining channel ${voiceChannelId} in guild ${guild.id}`);

  const connection = joinVoiceChannel({
    channelId: voiceChannelId,
    guildId: guild.id,
    adapterCreator,
  });

  connection.on('error', (err) => {
    console.error('[VoiceConnection] Error:', err.message);
  });

  try {
    await waitForReady(connection);
    console.log('[Voice] Connection is Ready');
  } catch (err) {
    connection.destroy();
    throw new Error(`Could not connect to voice channel: ${err.message}`);
  }

  const player = createAudioPlayer();

  connection.subscribe(player);

  session = {
    connection,
    player,
    queue: [],
    current: null,
    textChannelSend,
    guildId: guild.id,
  };

  sessions.set(guild.id, session);

  connection.on('stateChange', (oldState, newState) => {
    if (newState.status === VoiceConnectionStatus.Disconnected) {
      console.log('[Voice] Disconnected — cleaning up session');
      deleteSession(guild.id);
    }
  });

  player.on('error', (err) => {
    console.error('[Player] Error:', err.message);
    advanceQueue(guild.id);
  });

  player.on('stateChange', (oldState, newState) => {
    if (newState.status === AudioPlayerStatus.Idle && oldState.status !== AudioPlayerStatus.Idle) {
      advanceQueue(guild.id);
    }
  });

  return session;
}

async function advanceQueue(guildId) {
  const session = getSession(guildId);
  if (!session) return;

  if (!session.queue.length) {
    session.current = null;
    session.textChannelSend('Queue finished.').catch(() => {});
    return;
  }

  const track = session.queue.shift();
  session.current = track;

  try {
    // @jubbio/voice AudioResource takes a URL string; yt-dlp + ffmpeg handle extraction internally
    const resource = createAudioResource(track.url);
    session.player.play(resource);

    session.textChannelSend(
      `Now playing: **${track.title}** (${track.duration})${track.requestedBy ? ` — requested by ${track.requestedBy}` : ''}`
    ).catch(() => {});
  } catch (err) {
    console.error(`[Audio] Failed to play "${track.title}":`, err.message);
    session.textChannelSend(`Error playing **${track.title}**: ${err.message}`).catch(() => {});
    advanceQueue(guildId);
  }
}

module.exports = { resolveTrack, joinChannel, getSession, deleteSession, advanceQueue };
